on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, r: "release" }
          - { os: windows-latest, r: "devel" }
          - { os: macOS-latest, r: "release" }
          - { os: ubuntu-latest, r: "release" }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.config.os }}-${{ matrix.config.r }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
          extra-repositories: "https://r.docker.stat.auckland.ac.nz"

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: ${{ matrix.config.cache  }}
          needs: |
            check
            dependencies
          install-pandoc: true

      - uses: r-lib/actions/check-r-package@v2
